### ISSUE TITLE
Garageband から書き出すと音量小さくなってるぜ問題

### ISSUE THREAD

**Issue by gaaamii** [kumocast/kumocast.github.io#11]

**Comment by karur4n** [comment]
「自動ノーマライズ」をオフにすると、マスター音量が書き出したものにも反映されることを発見しました。

### 自動ノーマライズ

GarageBand > 環境設定... > 詳細 > 自動ノーマライズ

![2015-06-11 0 33 38](https://cloud.githubusercontent.com/assets/6816398/8086670/86dc2514-0fd1-11e5-8ea1-f48fc867dec6.png)

### マスター音量

メトロノームの横のメーター。画像は音量最大値。

![2015-06-11 0 24 49](https://cloud.githubusercontent.com/assets/6816398/8086416/4f332cda-0fd0-11e5-930a-90d71c1e5071.png)

## 書き出してみる

:hand: 結論を先に書くと、一番下の「 **自動ノーマライズ OFF, マスター音量 6.0 dB** 」 のみ音量が大きくなっている。

#### 自動ノーマライズ ON, マスター音量 0.0 dB

https://drive.google.com/file/d/0BzK_BPXz-s9NV3BNNWFHWWt5b0k/view?usp=sharing

#### 自動ノーマライズ OFF, マスター音量 0.0dB

https://drive.google.com/file/d/0BzK_BPXz-s9NZXJvdUhOMkxiODg/view?usp=sharing

#### 自動ノーマライズ ON, マスター音量 6.0 dB

https://drive.google.com/file/d/0BzK_BPXz-s9Nd2J2MVN6eGN3WDQ/view?usp=sharing

#### 自動ノーマライズ OFF, マスター音量 6.0 dB

https://drive.google.com/file/d/0BzK_BPXz-s9Na09QRGh4cm9sd1k/view?usp=sharing

## まとめ

「 **自動ノーマライズ OFF** 」にしてマスター音量を調整しましょう。いくつがいいかは検討。 6.0 dB だと音割れが聞こえる。 2 ~ 3.0 dB がいいかな。

## 参考

[GarageBand '11: 書き出したプロジェクトの音が小さすぎる](https://support.apple.com/kb/PH1809?locale=ja_JP&viewlocale=ja_JP)

**Comment by karur4n** [comment]
解決したっぽいので close します
