### ISSUE TITLE
音声ファイルのサイズがでかくなってしまう問題

### ISSUE THREAD

**Issue by gaaamii** [kumocast/kumocast.github.io#20]
辛辣でありがたいカスタマーレビューがついていました。
- https://itunes.apple.com/jp/podcast/kumokyasuto/id981382461

> ビットレートを意識しないのは、技術を語る以前のレベル。
> でかいファイルをダウンロードするのはムダでしかない。

**Comment by karur4n** [comment]
:star: 1 か.......

**Comment by gaaamii** [comment]
このつらい体験をバネにビッグになりましょう！（ちがう）

**Comment by karur4n** [comment]
ファイルサイズはどうなんでしょうね

例えば 23 回だと 1時間27分 で 76.4MB なので音声ファイルとしては大きすぎるっていうわけでもないと思います。

ビットレートは 128kbps です。

**Comment by moutend** [comment]
@gaaamii @karur4n 音声だけなら64kbpsで十分ですよー。(リスナーの素朴な意見)

**Comment by karur4n** [comment]
@moutend ご意見ありがとうございます！ :pray: 

そうですね 音質こだわれてないし、マイクを変更するなどがない限りこれからは 64 kbps でいきますか

**Comment by karur4n** [comment]
いつか聴き比べしましょう

**Comment by gaaamii** [comment]
64 kbps で何回かやって問題なさそうなので閉じます
