### ISSUE TITLE
iTunesに登録してるAuthorがUnknown

### ISSUE THREAD

**Issue by gaaamii** [kumocast/kumocast.github.io#21]

**Comment by karur4n** [comment]
iTunes Store で反映されたら close しましょう

**Comment by karur4n** [comment]
<img width="915" alt="2015-10-26 3 08 46" src="https://cloud.githubusercontent.com/assets/6816398/10717032/f64ea3e4-7b8e-11e5-891f-c35d7cf524bb.png">

カテゴリの横が反映されていない

っていうかテックニュースか（？）

**Comment by karur4n** [comment]
まだ完全ではないですが、あとは iTunes Store 待ちという状況なので close します

<img width="654" alt="2015-10-26 16 01 48" src="https://cloud.githubusercontent.com/assets/6816398/10723126/fcf8b966-7bfa-11e5-866b-0425b70fca3a.png">
