### ISSUE TITLE
BGM うざい問題

### ISSUE THREAD

**Issue by karur4n** [kumocast/kumocast.github.io#24]
全編を通して BGM が流れている必要はない気がしてきた。

導入部だけ流して、30秒ほどでフェードアウトすると良さそう。賛同を得られたら、次回から適用します。

**Comment by moutend** [comment]
:+1:

**Comment by karur4n** [comment]
爆速アグリー

**Comment by moutend** [comment]
10秒くらいでも良いのでは

**Comment by ayato-p** [comment]
:-1:

**Comment by karur4n** [comment]
意見が割れた

**Comment by ayato-p** [comment]
あの間抜けぽい BGM がないとくもキャスト感ない。あと単にうるさいだけならもう少し音量絞れば良いのでは(あまりうるさいと感じたことはない派の意見です

**Comment by karur4n** [comment]
年末年始の帰省時に電車で聴いてると、最初はいいんですけど、だんだんずっとループして流れている BGM がうっとうしく感じました。50分ほどずっと耳に入ってくるのはしんどい。

一般的なラジオも要所要所で特徴的な音楽が使われているけど、ずっと聴いてると「あれ 声だけになってる」ということが多いです。

もしくは 5 分間の音源を作って、10 ~ 30秒は いつもの BGM、残りは無音、をループさせるのもありかもしれません。

**Comment by gaaamii** [comment]
うーん、当事者なのにあまり頻繁に聴いてないから何とも言えない。確かに時間が長いとちょっとうっとうしいよなあ…

**Comment by karur4n** [comment]
実験的に一度それで公開してみてもいいかもしれません。

その場合は、第29回の僕の編集担当のもので行います

**Comment by ayato-p** [comment]
:+1:

**Comment by moutend** [comment]
:+1:

**Comment by gaaamii** [comment]
:)

**Comment by karur4n** [comment]
[Episode 28](http://kumocast.jp/2016/02/10/2016s-style.html) で実験したので、感想をどうぞ

僕はこちらの方が好きです。音がなくなるときはフェードアウトにしたほうがいいと思います。

**Comment by karur4n** [comment]
連携テスト

**Comment by ayato-p** [comment]
なんか寂しい…

**Comment by gaaamii** [comment]
聴いた感じ28回の感じよかったので29回もその感じで行きます
