### ISSUE TITLE
訂正のデザイン

### ISSUE THREAD

**Issue by karur4n** [kumocast/kumocast.github.io#3]
ベタ書きすると、こんな感じで見づらいので良くない

![2015-05-10 19 17 06](https://cloud.githubusercontent.com/assets/6816398/7553882/2d642fcc-f749-11e4-9dec-399b65b297c1.png)

**Comment by gaaamii** [comment]
訂正はblogサブドメインのタンブラーブログの方へ委譲したのでこのissueは閉じます
